### ISSUE TITLE
SMSContact equals

### ISSUE THREAD

**Issue by ricdezen** [RicDeZen/ingsw-group1-findmyphone#19]
`SMSContact` uses both its fields in the equals override, but its primary key is only the address, this is a contraddiction, because we can have contacts with the same address and different names, but we will never be able to store them both in the database.
This might seem like it's not a problem, because the Contact can just be updated when a new name is found, but some tests should be written to ensure the database (or at least the manager) works as intended.
Besides, this also implies you can add different addresses for a same contact name. If this is intended, it should be clearly stated in the specs.

**Comment by turcato-niccolo** [comment]
> Besides, this also implies you can add different addresses for the same contact name. If this is intended, it should be clearly stated in the specs.

Well homonymy is possible

> but some tests should be written to ensure the database (or at least the manager) works as intended.

The primary key you set for SMSContact is the phone address, we should be pretty much fine, should be able to write some tests tomorrow
```
@PrimaryKey
    @ColumnInfo(name = ADDRESS_COLUMN_NAME)
    private String address; //address: phone number
```
