### ISSUE TITLE
Improper scope for LocationMessageHelper

### ISSUE THREAD

**Issue by ricdezen** [RicDeZen/ingsw-group1-findmyphone#9]
Class `LocationMessageHelper` is a public class, but its constants appear to need package private scope for testing, this is a symptom of either:
- Bad specs
- Wrong tests
- Wrong scope

Everyone is invited to try and figure out a better architechture for the class, maybe there is something that should be done differently, maybe it should be done somewhere else.
This is not a urgent issue, just a good exercise in my opinion.

**Comment by turcato-niccolo** [comment]
I don't see how defining the constants of this class as private could be useful, at the end of the day the message syntax can be seen simply by calling its methods.
As the IDE suggests we could define the constants package-private, but it has sense as long as all the other methods have the same scope.
So what I'm saying is essentially the whole class should be package-private.

**Comment by ricdezen** [comment]
> So what I'm saying is essentially the whole class should be package-private.
I agree, it probably could, I think tests should be adjusted for that tho

**Comment by ricdezen** [comment]
Yo aint nobody got time for that
